apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-ms
  labels:
    app: user-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-ms
  template:
    metadata:
      labels:
        app: user-ms
    spec:
      restartPolicy : OnFailure
      containers:
        - name: user-ms
          image: islamahmad/eauser-ms:1.0.0
          # ports:
          #   – containerPort: 8080
          resources:
            requests:
              memory: "32Mi"
              cpu: "125m"
            limits:
              memory: "64Mi"
              cpu: "250m"
          livenessProbe:
              httpGet:
                path: /user_ms_liveness
                port: 8080

          env:
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PORT
              value: "3306"
            - name: SERVICE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: user-ms
                  key: SERVICE_API_KEY
            - name: MYSQL_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: user-ms
                  key: MYSQL_PASSWORD
            - name: AUTHENTICATE_SERVICE
              valueFrom:
                configMapKeyRef:
                 name: user-ms
                 key: AUTHENTICATE_SERVICE